@baseUrl = https://6a83-2400-1a00-1b67-2848-44b1-3293-826e-bd5c.ngrok-free.app
@userId = 6a551661cf273a980ecdd99c
@tripId = 6a65bbae65c37f485de2d5d7
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTU1MTY2MWNmMjczYTk4MGVjZGQ5OWMiLCJpYXQiOjE3ODU0OTE2NzMsImV4cCI6MTc4NTU3ODA3M30.nGPIKCOSRRoEA4SPqR7F_gKojyiUEOjbLvcsSPpJakE
@tripToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlwSWQiOiI2YTcwN2I3MTU1NjM5NmQxNDhlNTJjMTciLCJpYXQiOjE3ODU4NDM2NzksImV4cCI6MTc4NTg0NzI3OX0.DCyqL_1qJVYQyPgPGMwN55egJm6ep_eEtR1YEqt__8s


### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe97@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

### REGISTER USER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Jae Doe",
  "email": "jae.doe2@example.com",
  "password": "test123"
}

### LOGIN USER
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "jane.doe2@example.com",
  "password": "test123"
}

### CREATE TRIP
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}

### GET ALL TRIPS
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### GET TRIP BY ID
GET {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### UPDATE TRIP BY ID
PATCH {{baseUrl}}/trips/{{tripId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon and back",
  "budget": {
    "total": 1500
  }
}

### DELETE TRIP BY ID
DELETE {{baseUrl}}/trips/{{tripId}}
Authorization: Bearer {{token}}

### CREATE BAGGAGE
POST {{baseUrl}}/{{tripId}}/baggages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jacket"

}


### SEND TRIP INVITATION
POST {{baseUrl}}/trips/{{tripId}}/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "collaboratorEmails": [
    "jane@example.com"
  ]
}

### ACCEPT TRIP INVITATION
GET {{baseUrl}}/trips/{{tripId}}/invite/accept?token={{tripToken}}
Authorization: Bearer {{token}}

